/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PLATFORM:     HT-PICC18
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS               4  // Number of tasks that can be active at one time
#define OS_DISABLE_PRIORITY        // 
#define OS_TIMER_ENABLE

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

//#define OS_ENABLE_CRITICAL_SECTION // Enable critical sections services






//------------------------------------------------------------------------------
// BSEMS
//------------------------------------------------------------------------------

#define OS_BSEMS               5  // Number of binary semaphores

enum OSA_BSEMS_ENUM
{
    BS_ADC_START,    
    BS_DISPLAY,
    BS_RAM_REFRASH,
    BS_PWM,
    BS_PWM_RESET   
};


//------------------------------------------------------------------------------
// STIMERS
//------------------------------------------------------------------------------



#endif
